---
title: "Solo 2 Prep"
output:
  pdf_document: default
  html_notebook: default
---
# Chapter 1 Prep

There are 3 choice for 36 choice sets.Total of 108. There are 424 respondants

```{r}
load("stc-cbc-respondents-v3(1).RData")

skimr::skim(resp.data.v3)
```

Viewing Task matrix and creating dummy variable

```{r}
library(dummies)
load("efCode.RData") 
taskV3 <- read.csv("stc-dc-task-cbc -v3(1).csv", sep="\t")
head(taskV3)
task.mat <- as.matrix(taskV3[, c("screen", "RAM", "processor", "price", "brand")])
X.mat=efcode.attmat.f(task.mat) 

head(X.mat)
```

Create price brand interacton

```{r}
pricevec <- taskV3$price-mean(taskV3$price)

# brand columns
X.brands <- X.mat[,9:11]
X.BrandByPrice = X.brands*pricevec 

X.matrix=cbind(X.mat,X.BrandByPrice) 

# Check if the data came through well
det(t(X.matrix)%*%X.matrix)
```

```{r}
ydata <- resp.data.v3[,4:39]

# making sure we got all the 36 choice sets

ydata=na.omit(ydata)
ydata <- as.matrix(ydata)

zowner <- 1 * ( ! is.na(resp.data.v3$vList3) )

```

```{r}
library(bayesm)
lgtdata = NULL 

# The lgtdata is required argument for MCMC HBMNL regression where lgtdata is a list of list of length equal to # of respondents. Each list in the list contains y and the X.matrix
for (i in 1:424) { 
lgtdata[[i]]=list(y=ydata[i,],X=X.matrix) 
} 
```


We'll try MCMC for some samples of data


```{r}
lgtdata100 = lgtdata[1:100]
mcmctest = list(R=5000,keep =5)
Data1=list(p=3,lgtdata=lgtdata100)   # p is choice set size

testrun1=rhierMnlDP(Data=Data1,Mcmc=mcmctest)
```

Lets examine the output

```{r}
names(testrun1)

dim(testrun1$betadraw) # first dimension is the # of respondents, the second is the # parameters (betas) and the third is the # iterations - see mcmctest variable
```

```{r}
plot(1:length(testrun1$betadraw[1,1,]),testrun1$betadraw[1,1,])
betadraw1 <- testrun1$betadraw
plot(betadraw1[1,1,])
plot(density(betadraw1[1,14,701:1000],width=2))

betameans <- apply(betadraw1[,,701:1000],c(1,2),mean) 

dim(betameans)
dim(X.matrix)

xbeta=X.matrix%*%t(betameans)

xbeta2=matrix(xbeta,ncol=3,byrow=T)


```
xbeta2 is noting but the log odds of the choice sets now. We need to be converting it into probabilities

```{r}
expxbeta2=exp(xbeta2)

rsumvec=rowSums(expxbeta2) 

pchoicemat=expxbeta2/rsumvec 

custchoice <- max.col(pchoicemat)

ydata2 <- as.vector(t(ydata))[1:length(custchoice)]
```

